version: 1.0.{build}

skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

platform: Any CPU

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  project: ZSpriteTools.sln

after_build:
- 7z a ZSpriteTools-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\ZSpriteTools\bin\%CONFIGURATION%\SpriteLibrary.dll
- 7z a ZSpriteTools-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\ZSpriteTools\bin\%CONFIGURATION%\ZSpriteTools.exe
- 7z a ZSpriteTools-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\ZSpriteTools\bin\%CONFIGURATION%\ZSpriteTools.exe.config

artifacts:
- path: SpriteLibrary\bin\%CONFIGURATION%\SpriteLibrary.dll
- path: ZSpriteTools-$(appveyor_build_version).zip

deploy:
- provider: GitHub
  auth_token:
    secure: ViWNMG9POKQc60IVRa88gr+T8To/aPCGDMn8xGVPGACQYx/sESKtXg77AS/LQt0F
  draft: false
